project:
  type: website

website:
  title: "Bioconductor community blog"
  site-url: https://bioconductor.github.io/biocblog/
  description: "A blog for the Bioconductor community!"
  navbar:
    right:
      - about.qmd
      - contributing.qmd
      - icon: github
        href: https://github.com/bioconductor/biocblog
      - icon: twitter
        href: https://twitter.com/bioconductor
      - icon: youtube
        href: https://www.youtube.com/user/bioconductor
      - icon: slack
        href: https://bioc-community.herokuapp.com/
      - icon: rss
        href: index.xml
format:
  html:
    theme: yeti
    css: styles.css
