on:
  push:
    branches: 
    - main
    - CuratedAtlasQueryR # allow while sharing preview
    
env:
  cache-version: v1
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}


name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_16

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Query dependencies and update old packages
        run: |
          BiocManager::install(c("jsonlite", "htmltools", "rmarkdown", "RefManageR"))
          BiocManager::install("stemangiola/CuratedAtlasQueryR")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
